/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import java.util.*;

/**
 *
 * @author mitp1_900
 */
public class logoQuiz extends javax.swing.JFrame {

    /**
     * Creates new form logoQuiz
     */
    public logoQuiz() {
        initComponents();
    }
    public Rectangle playButton = new Rectangle(logoQuiz.WIDTH / 2 + 120, 150, 150, 50); 
    public Rectangle helpButton = new Rectangle(logoQuiz.WIDTH / 2 + 120, 250, 150, 50);
    public Rectangle quitButton = new Rectangle(logoQuiz.WIDTH / 2 + 120, 350, 150, 50);
    
    // Declares the arraylist for all of the logos.
    public ArrayList <ImageIcon> logoList = new ArrayList <ImageIcon>();
    public ArrayList <String>logoAnswers = new ArrayList <String>();
    
    ImageIcon amd = new ImageIcon("amd.png");
    ImageIcon adb = new ImageIcon("adb.png");
    ImageIcon add = new ImageIcon("add.png");
    ImageIcon app = new ImageIcon("apple.png");
    ImageIcon bk = new ImageIcon("bk.png");
    ImageIcon cola = new ImageIcon("cola.png");
    ImageIcon dell = new ImageIcon("dell.png");
    ImageIcon ggl = new ImageIcon("google.png");
    ImageIcon itl = new ImageIcon("intel.png");
    ImageIcon kfc = new ImageIcon("kfc.png");
    ImageIcon lct = new ImageIcon("lacoste.png");
    ImageIcon log = new ImageIcon("logi.png");
    ImageIcon mcd = new ImageIcon("McD.png");
    ImageIcon nike = new ImageIcon("nike.png");
    ImageIcon nin = new ImageIcon("nin.png");
    ImageIcon nvd = new ImageIcon("nvidia.png");
    ImageIcon pep = new ImageIcon("pepsi.png");
    ImageIcon sbw = new ImageIcon("subway.png");
    ImageIcon twt = new ImageIcon("twitter.png");
    ImageIcon win = new ImageIcon("windows.png");
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icoLogo = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTitle.setText("Logo Quiz");

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        jLabel1.setText("CaSe-SeNsItIvE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnStart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblTitle))
                .addGap(18, 18, 18)
                .addComponent(btnEnter)
                .addGap(42, 42, 42)
                .addComponent(btnNext)
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(icoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(69, 69, 69)
                .addComponent(icoLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnStart)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private enum STATE {
        MENU,
        GAME 
    }
    
    // Variable to check what state the game is in
    private STATE state = STATE.MENU; 
    
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        // disables next button
        btnNext.setEnabled(false);
        logoList.add(adb);
        logoList.add(amd);
        logoList.add(add);
        logoList.add(app);
        logoList.add(bk);
        logoList.add(cola);
        logoList.add(dell);
        logoList.add(ggl);
        logoList.add(itl);
        logoList.add(kfc);
        logoList.add(lct);
        logoList.add(log);
        logoList.add(mcd);
        logoList.add(nike);
        logoList.add(nin);
        logoList.add(nvd);
        logoList.add(pep);
        logoList.add(sbw);
        logoList.add(twt);
        logoList.add(win);
        
        logoAnswers.add("Adobe");
        logoAnswers.add("AMD");
        logoAnswers.add("Adidas");
        logoAnswers.add("Apple");
        logoAnswers.add("Burger King");
        logoAnswers.add("Coca-Cola");
        logoAnswers.add("Dell");
        logoAnswers.add("Google");
        logoAnswers.add("Intel");
        logoAnswers.add("KFC");
        logoAnswers.add("Lacoste");
        logoAnswers.add("Logitech");
        logoAnswers.add("McDonalds");
        logoAnswers.add("Nike");
        logoAnswers.add("Nintendo");
        logoAnswers.add("Nvidia");
        logoAnswers.add("Pepsi");
        logoAnswers.add("Subway");
        logoAnswers.add("Twitter");
        logoAnswers.add("Windows");
        
        icoLogo.setIcon(logoList.get(0));
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:

        int k = logoList.indexOf(icoLogo.getIcon());
        icoLogo.setIcon(logoList.get(k + 1));
        btnNext.setEnabled(false);
        txtInput.setText("");
        

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        int k = logoList.indexOf(icoLogo.getIcon());
        // gets user input
        String userAnswer = txtInput.getText();
        // disables button
        if (userAnswer.equals(logoAnswers.get(k))) {
            btnNext.setEnabled(true);
            txtInput.setText("Correct! Please Click Next!");
        } else {
            txtInput.setText("Incorrect! Try Again!");
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logoQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logoQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logoQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logoQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logoQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel icoLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
