package logoquiz;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.ImageIcon;
import java.util.*;

/**
 *
 * @author mitp1_900
 */
public class logoQuiz extends javax.swing.JFrame {

    /**
     * Creates new form logoQuiz
     */
    public logoQuiz() {
        initComponents();
    }

    // global variable for score 
    public static int score; 
    
    // Declares the arraylist for all of the logos.
    public ArrayList <ImageIcon> logoList = new ArrayList <ImageIcon>();
    public ArrayList <String>logoAnswers = new ArrayList <String>();
    public ArrayList <String>logoHint = new ArrayList <String>();
    
    // inserting logos into array 
    ImageIcon amd = new ImageIcon("amd.png");
    ImageIcon adb = new ImageIcon("adb.png");
    ImageIcon add = new ImageIcon("add.png");
    ImageIcon app = new ImageIcon("apple.png");
    ImageIcon bk = new ImageIcon("bk.png");
    ImageIcon cola = new ImageIcon("cola.png");
    ImageIcon dell = new ImageIcon("dell.png");
    ImageIcon ggl = new ImageIcon("google.png");
    ImageIcon itl = new ImageIcon("intel.png");
    ImageIcon kfc = new ImageIcon("kfc.png");
    ImageIcon lct = new ImageIcon("lacoste.png");
    ImageIcon log = new ImageIcon("logi.png");
    ImageIcon mcd = new ImageIcon("McD.png");
    ImageIcon nike = new ImageIcon("nike.png");
    ImageIcon nin = new ImageIcon("nin.png");
    ImageIcon nvd = new ImageIcon("nvidia.png");
    ImageIcon pep = new ImageIcon("pepsi.png");
    ImageIcon sbw = new ImageIcon("subway.png");
    ImageIcon twt = new ImageIcon("twitter.png");
    ImageIcon win = new ImageIcon("windows.png");
    
 
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icoLogo = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        lblTitleImage = new javax.swing.JLabel();
        btnHint = new javax.swing.JButton();
        txtHint = new javax.swing.JTextArea();
        txtScore = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(699, 506, 506, 506));
        setMaximumSize(new java.awt.Dimension(710, 520));
        setMinimumSize(new java.awt.Dimension(710, 520));
        getContentPane().setLayout(null);
        getContentPane().add(icoLogo);
        icoLogo.setBounds(210, 180, 260, 210);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext);
        btnNext.setBounds(550, 410, 55, 23);

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart);
        btnStart.setBounds(140, 410, 60, 23);

        txtInput.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });
        getContentPane().add(txtInput);
        txtInput.setBounds(210, 410, 260, 30);

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnter);
        btnEnter.setBounds(480, 410, 59, 23);

        lblTitleImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoquiz/league of logos logo.png"))); // NOI18N
        getContentPane().add(lblTitleImage);
        lblTitleImage.setBounds(220, 0, 230, 140);

        btnHint.setText("Hint");
        btnHint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHintActionPerformed(evt);
            }
        });
        getContentPane().add(btnHint);
        btnHint.setBounds(140, 450, 60, 23);

        txtHint.setColumns(20);
        txtHint.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtHint.setRows(5);
        getContentPane().add(txtHint);
        txtHint.setBounds(210, 450, 260, 30);

        txtScore.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        getContentPane().add(txtScore);
        txtScore.setBounds(300, 150, 84, 22);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(480, 450, 60, 23);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoquiz/background.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 710, 520);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 170, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents
 

    
    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        
        // disables next button
        btnNext.setEnabled(false);
        // calls logo list and titles array
        listAdd();
        // gets first icon of the array
        icoLogo.setIcon(logoList.get(0));


        
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        
        //
        int k = logoList.indexOf(icoLogo.getIcon());
        
        //
        icoLogo.setIcon(logoList.get(k + 1));
        
        // Disables button
        btnNext.setEnabled(false);
        
        // Clears the text fields
        txtInput.setText("");
        txtHint.setText("");
        

    }//GEN-LAST:event_btnNextActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        
        // assigns int k to index of array
        int k = logoList.indexOf(icoLogo.getIcon());
        
        // gets user input
        String userAnswer = txtInput.getText();
        // if statment to check if user input is equal to corresponding logo name
        // if correct, next button is enabled and 10 points are added to score
        // else incorrect message is displayed and 2 points are deducted
        if (userAnswer.equals(logoAnswers.get(k))) {
            btnNext.setEnabled(true);
            txtInput.setText("Correct! Please Click Next!");
            score += 10;
            txtScore.setText("Score: " + Integer.toString(score));
        } else {
            txtInput.setText("Incorrect! Try Again!");
            score -= 2;
            txtScore.setText("Score: " + Integer.toString(score));
        }
 
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        // Exits the application
            System.exit(0);  
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputActionPerformed

    private void btnHintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHintActionPerformed
        // TODO add your handling code here:
        
        int k = logoList.indexOf(icoLogo.getIcon());
        txtHint.setText(logoHint.get(k));
             
       
    }//GEN-LAST:event_btnHintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(logoQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(logoQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(logoQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(logoQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logoQuiz().setVisible(true);
            }
        });
    }
    // global method
    public void listAdd () {
        // array date for logo images
        logoList.add(adb);
        logoList.add(amd);
        logoList.add(add);
        logoList.add(app);
        logoList.add(bk);
        logoList.add(cola);
        logoList.add(dell);
        logoList.add(ggl);
        logoList.add(itl);
        logoList.add(kfc);
        logoList.add(lct);
        logoList.add(log);
        logoList.add(mcd);
        logoList.add(nike);
        logoList.add(nin);
        logoList.add(nvd);
        logoList.add(pep);
        logoList.add(sbw);
        logoList.add(twt);
        logoList.add(win);
        
        // array date for logo names
        logoAnswers.add("Adobe");
        logoAnswers.add("AMD");
        logoAnswers.add("Adidas");
        logoAnswers.add("Apple");
        logoAnswers.add("Burger King");
        logoAnswers.add("Coca-Cola");
        logoAnswers.add("Dell");
        logoAnswers.add("Google");
        logoAnswers.add("Intel");
        logoAnswers.add("KFC");
        logoAnswers.add("Lacoste");
        logoAnswers.add("Logitech");
        logoAnswers.add("McDonalds");
        logoAnswers.add("Nike");
        logoAnswers.add("Nintendo");
        logoAnswers.add("Nvidia");
        logoAnswers.add("Pepsi");
        logoAnswers.add("Subway");
        logoAnswers.add("Twitter");
        logoAnswers.add("Windows");
        
        // array date for logo hints
        logoHint.add("Creator of Photoshop..."); 
        logoHint.add("Processors and Graphics Cards"); 
        logoHint.add("Rivarly with Nike");
        logoHint.add("Steve Jobs");
        logoHint.add("acquired Tim Hortons");
        logoHint.add("Rivarly with Pepsi");
        logoHint.add("Inspiron Laptop Series");
        logoHint.add("Now under the name Alphabet");
        logoHint.add("acquired Tim Hortons");
        logoHint.add("World best processors");
        logoHint.add("Fried Chicken");
        logoHint.add("Life Is a Beautiful Sport..");
        logoHint.add("Computer accessories ");
        logoHint.add("I'm lovin it");
        logoHint.add("Check mark");
        logoHint.add("Mario");
        logoHint.add("Graphics Cards");
        logoHint.add("Rivarly with Coca Cola");
        logoHint.add("5 dollar foot long");
        logoHint.add("Blue Bird");
        logoHint.add("Microsoft's invention");
        
        
        
        
        
        
        
        

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHint;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel icoLogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTitleImage;
    private javax.swing.JTextArea txtHint;
    private javax.swing.JTextField txtInput;
    private javax.swing.JLabel txtScore;
    // End of variables declaration//GEN-END:variables
}
